### ISSUE TITLE
Cannot install when downloading from market place with older VS version installed

### ISSUE THREAD

**Issue by szilardd** [philippdolder/NoMorePanicSave2017#1]
Hi,

I'm trying to install the extension but it fails with message "This extension is not installable on any currently installed products"

I have Visual Studio 2015 and 2017 Enterprise installed. From the log file it seems like it doesn't detect the 2017 version.

Here is the install log:

3/27/2017 16:21:10 - Microsoft VSIX Installer
3/27/2017 16:21:10 - -------------------------------------------
3/27/2017 16:21:10 - Initializing Install...
3/27/2017 16:21:10 - Extension Details...
3/27/2017 16:21:10 - 	Identifier         : NoMorePanicSave.Philipp Dolder.862684fa-62bb-4fa7-bd83-3fdc294b5a3f
3/27/2017 16:21:10 - 	Name               : NoMorePanicSave2017
3/27/2017 16:21:10 - 	Author             : Philipp Dolder
3/27/2017 16:21:10 - 	Version            : 1.0
3/27/2017 16:21:10 - 	Description        : Automatically saves all files and projects when leaving the current visual studio instance
3/27/2017 16:21:10 - 	Locale             : en-US
3/27/2017 16:21:10 - 	MoreInfoURL        : https://github.com/philippdolder/NoMorePanicSave2017
3/27/2017 16:21:10 - 	InstalledByMSI     : False
3/27/2017 16:21:10 - 	SupportedFrameworkVersionRange : [4.5,)
3/27/2017 16:21:10 - 
3/27/2017 16:21:10 - 	SignatureState     : Unsigned
3/27/2017 16:21:10 - 	Supported Products : 
3/27/2017 16:21:10 - 		Microsoft.VisualStudio.Community
3/27/2017 16:21:10 - 			Version : [15.0,16.0)
3/27/2017 16:21:10 - 		Microsoft.VisualStudio.Pro
3/27/2017 16:21:10 - 			Version : [15.0,16.0)
3/27/2017 16:21:10 - 		Microsoft.VisualStudio.Enterprise
3/27/2017 16:21:10 - 			Version : [15.0,16.0)
3/27/2017 16:21:10 - 
3/27/2017 16:21:10 - 	References         : 
3/27/2017 16:21:10 - 		-------------------------------------------------------
3/27/2017 16:21:10 - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
3/27/2017 16:21:10 - 		Name         : Visual Studio MPF 15.0
3/27/2017 16:21:10 - 		Version      : [15.0]
3/27/2017 16:21:10 - 		MoreInfoURL  : 
3/27/2017 16:21:10 - 		Nested       : No
3/27/2017 16:21:10 - 
3/27/2017 16:21:10 - Signature Details...
3/27/2017 16:21:10 - 	Extension is not signed.
3/27/2017 16:21:10 - 
3/27/2017 16:21:10 - Searching for applicable products...
3/27/2017 16:21:10 - Found installed product - Microsoft Visual Studio Enterprise 2015
3/27/2017 16:21:10 - Found installed product - Microsoft Visual Studio Professional 2015
3/27/2017 16:21:10 - Found installed product - Microsoft Visual Studio Community 2015
3/27/2017 16:21:10 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
3/27/2017 16:21:10 - Found installed product - Global Location
3/27/2017 16:21:10 - Found installed product - ssms
3/27/2017 16:21:10 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by philippdolder** [comment]
That's strange. Except declaring the supported versions and editions in the extension, I have no control over  the installation process.

Did you download from the market place or install it from within Visual Studio `Extensions and Updates` dialog? I installed it on 2 different machines running VS 2017 Enterprise from the dialog without a problem.

Which exact version of VS 2017 do you have? It certainly is RTM, right?
Currently I can only guess what's the issue. Can you please tell me which of the Visual Studio 2017 workloads you have installed?

**Comment by szilardd** [comment]
I was trying to install from the marketplace (https://marketplace.visualstudio.com/items?itemName=PhilippDolder.NoMorePanicSave2017)

Now I tried from Visual Studio -> Extensions and Updates and it worked. 

Thanks for taking time to make this extension.

Maybe the marketplace has a wrong version. In case you still need them, my workloads are:

.NET desktop environment
ASP.NET and web development
.NET Core cross-platform development
Visual Studio Build Tools

I'm also using VS 2017 Enterprise

**Comment by philippdolder** [comment]
Thanks. Glad you managed to install it :-)
I just tried the download from the market place and install it then, worked on my machine.
But I have different workloads than you.

I'll investigate further on a VM.
Could you please tell me the exact version number of your VS 2017 installation? You can find it in `Help -> About Visual Studio`

Thank you

![image](https://cloud.githubusercontent.com/assets/437134/24359711/745bea58-1305-11e7-89cd-f4a0f90f9105.png)

**Comment by szilardd** [comment]
Here is the info and other installed extensions. I'm on Win 10 Pro

Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Visual Basic 2017   00369-60000-00001-AA779
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA779
Microsoft Visual C# 2017

ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NoMorePanicSave2017   1.0
Automatically saves all files and projects when leaving the current visual studio instance

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Project File Tools   1.0.1
Provides Intellisense and other tooling for XML based project files such as .csproj and .vbproj files.

Redgate ReadyRoll   1.13.22.3204
Extend DevOps processes to your SQL Server databases and safely automate database deployments.  

Redgate SQL Prompt   7.4.1.767
Write, format, and refactor SQL effortlessly

Redgate SQL Search   2.3.10.1131
Search functionality for SQL Server databases, from within Visual Studio

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

**Comment by philippdolder** [comment]
As described in http://stackoverflow.com/questions/42817874/visual-studio-2017-is-not-detected-by-extensions-for-installation it seems to be a problem with an older VSIX installer executable (in this case from VS2015) trying to make sense of the VS2017 vsix package as it is assigned as the default program for vsix files.

**SOLUTION**
Install from within extensions & updates inside of Visual Studio 2017

**WORKAROUND** (only suggested when you absolutely require an offline installer)
when downloading from marketplace make sure to execute the downloaded VSIX file with the 2017 vsix installer, located in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe` either from command line or using the `open with...` context menu entry.
