### ISSUE TITLE
Any cause to hope for a 2019 version?

### ISSUE THREAD

**Issue by aheward** [philippdolder/NoMorePanicSave2017#12]
VS 2019 is out and is unfortunately not compatible with the 2017 version.

No pressure! I'm just crossing my fingers that you're planning to do another update.

**Comment by philippdolder** [comment]
@aheward NoMorePanicSave2017 is compatible with VS 2019. See #7 
I'll make it more obvious on the VS extensions gallery site https://marketplace.visualstudio.com/items?itemName=PhilippDolder.NoMorePanicSave2017

Please report back if you find any issues

**Comment by RobbSadler** [comment]
This is the issue I had - Is it simply not possible, or requires a major refactor?

**Comment by philippdolder** [comment]
@RobbSadler The required major refactoring has been done already.
NoMorePanicSave2017 should work just fine in VS 2019. Were you able to install it in VS 2019?

**Comment by aheward** [comment]
It's working fine for me in VS2019.
