### ISSUE TITLE
Support VS2109

### ISSUE THREAD

**Issue by ArgTang** [philippdolder/NoMorePanicSave2017#7]
I like this plugin very much, but it is not available for VS2019.

**Comment by philippdolder** [comment]
Thank you. I will take a look into making it work with the VS 2019 preview.
A PR would be highly appreciated of course :-)

**Comment by ArgTang** [comment]
Hi! 
I haven't done any extension development before so i tried a little bit, updated manifest and packages (and changed to package refs)
It builds and installs but does not work. Cant find anything in ActivityLog.xml, so i don't know where to go from there

**Comment by philippdolder** [comment]
thanks for giving it a try. You'll need a bit of patience, but I hope I can get a serious look into it around Christmas.

**Comment by motivity-chris** [comment]
FWIW, this is even more desirable now that VS 2019 has been fully released

**Comment by philippdolder** [comment]
@motivity-chris I'm at it currently. I think I've done all required changes, but I need to properly set up my environment to build it and test it out.

**Comment by boulix3** [comment]
Hello,
After cloning your repository, I built it and installed it using the vsix located in the bin\debug folder.

The extension works fine with Visual Studio 2019, but the following warning pops up : 
`This extension uses deprecated APIs and will not be compatible with a future Visual Studio Update.`
I'm not sure, but I think it is related to this : https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2019

Thanks a lot for your work on this extension 👍.

**Comment by boulix3** [comment]
This pull request fixes the warning when using the extension in vs2019.
#8

**Comment by philippdolder** [comment]
@boulix3 thank you. I will have a look into it over easter.

**Comment by philippdolder** [comment]
I have published a new version (1.2) which supports VS 2019. You will get the notification above, mentioned by @boulix3.

Current state is: The extension is working, but it is not future proof.
Twitter announcement: https://twitter.com/philippdolder/status/1122498819223105536

I'm still trying to figure out how to make it all work with the new async package API. @boulix3 unfortunately only eliminates the warnings, but renders the extension useless as its internals need to be built completely different.

**Comment by philippdolder** [comment]
I created a new issue #9 for the API change

**Comment by philippdolder** [comment]
@ArgTang the latest version published in the VS Extensions Gallery supports VS2019 without the warning https://marketplace.visualstudio.com/items?itemName=PhilippDolder.NoMorePanicSave2017
