### ISSUE TITLE
Migrate to Async package API

### ISSUE THREAD

**Issue by philippdolder** [philippdolder/NoMorePanicSave2017#9]
Some links:
https://devblogs.microsoft.com/visualstudio/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/

https://github.com/Microsoft/vs-threading/blob/master/doc/cookbook_vs.md

https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background?view=vs-2019

https://www.nuget.org/packages/Microsoft.VisualStudio.SDK.Analyzers

https://devblogs.microsoft.com/visualstudio/troubleshooting-extensions-with-the-activity-log/

**Comment by daberni** [comment]
looks like the APIs got removed in the latest Visual Studio 2019 Version 16.1 Preview 3

**Comment by philippdolder** [comment]
Which means the extension will be useless after the 16.1 RTM :-(
I must admit: As I'm not using VS anymore, but rather use JetBrains Rider all day, the time I'm willing to invest to do the migration is rather limited.

**Comment by philippdolder** [comment]
@daberni @boulix3
Can you please share your Twitter handles with me, so that I can mention you in the tweet to announce the new release

**Comment by boulix3** [comment]
> Can you please share your Twitter handles with me, so that I can mention you in the tweet to announce the new release

I don't have a twitter account.

**Comment by daberni** [comment]
I guess you already got mine 😄 `@da_berni_`

**Comment by philippdolder** [comment]
Thanks again guys for your support.
https://twitter.com/philippdolder/status/1132983229651271681
